import type { VideoResult } from "./types";

export const mockVideos: VideoResult[] = [
  {
    id: "v1",
    title: "Java Full Course 2024 - Beginner to Advanced | Complete Java Tutorial",
    channelName: "Programming with Mosh",
    channelId: "c1",
    thumbnail: "https://img.youtube.com/vi/eIrMbAQSU34/maxresdefault.jpg",
    duration: "12:04:32",
    durationSeconds: 43472,
    views: 4200000,
    likes: 185000,
    likeRatio: 4.4,
    sentimentScore: 87,
    syllabusMatch: 92,
    overallScore: 91,
    publishedAt: "2024-01-15",
    isPlaylist: false,
    subscriberCount: 3800000,
    channelAgeYears: 10,
    description: "Complete Java tutorial covering OOP, Data Structures, Spring Boot...",
    topicsDetected: ["OOP", "Data Structures", "Spring Boot", "JDBC", "Collections", "Multithreading"],
  },
  {
    id: "v2",
    title: "Java Programming Full Course | Java Tutorial for Beginners",
    channelName: "Telusko",
    channelId: "c2",
    thumbnail: "https://img.youtube.com/vi/BGTx91t8q50/maxresdefault.jpg",
    duration: "8:30:15",
    durationSeconds: 30615,
    views: 2800000,
    likes: 142000,
    likeRatio: 5.07,
    sentimentScore: 82,
    syllabusMatch: 78,
    overallScore: 84,
    publishedAt: "2023-09-20",
    isPlaylist: true,
    subscriberCount: 2100000,
    channelAgeYears: 12,
    description: "Learn Java from scratch. This tutorial covers basics to advanced concepts.",
    topicsDetected: ["Variables", "OOP", "Exception Handling", "File I/O", "Lambda"],
  },
  {
    id: "v3",
    title: "Java Complete Course in Hindi | Java Full Course for Beginners to Advanced",
    channelName: "CodeWithHarry",
    channelId: "c3",
    thumbnail: "https://img.youtube.com/vi/ntLJmg6PJQY/maxresdefault.jpg",
    duration: "15:22:48",
    durationSeconds: 55368,
    views: 8500000,
    likes: 320000,
    likeRatio: 3.76,
    sentimentScore: 90,
    syllabusMatch: 95,
    overallScore: 88,
    publishedAt: "2023-03-12",
    isPlaylist: true,
    subscriberCount: 15000000,
    channelAgeYears: 9,
    description: "Complete Java course in Hindi covering everything from basics to advanced topics.",
    topicsDetected: ["Variables", "OOP", "Collections", "JDBC", "Spring", "Multithreading", "Design Patterns"],
  },
  {
    id: "v4",
    title: "Learn Java in 14 Minutes (seriously)",
    channelName: "Alex Lee",
    channelId: "c4",
    thumbnail: "https://img.youtube.com/vi/RRubcjpTkks/maxresdefault.jpg",
    duration: "0:14:00",
    durationSeconds: 840,
    views: 3100000,
    likes: 98000,
    likeRatio: 3.16,
    sentimentScore: 74,
    syllabusMatch: 22,
    overallScore: 52,
    publishedAt: "2022-05-18",
    isPlaylist: false,
    subscriberCount: 580000,
    channelAgeYears: 7,
    description: "Quick crash course on Java basics.",
    topicsDetected: ["Variables", "Loops", "Methods"],
  },
  {
    id: "v5",
    title: "Java + DSA + Interview Preparation Course",
    channelName: "Kunal Kushwaha",
    channelId: "c5",
    thumbnail: "https://img.youtube.com/vi/rZ41y93P2Qo/maxresdefault.jpg",
    duration: "24:10:55",
    durationSeconds: 87055,
    views: 5600000,
    likes: 245000,
    likeRatio: 4.37,
    sentimentScore: 93,
    syllabusMatch: 85,
    overallScore: 89,
    publishedAt: "2023-07-01",
    isPlaylist: true,
    subscriberCount: 900000,
    channelAgeYears: 4,
    description: "Complete Java DSA and interview prep course with practice problems.",
    topicsDetected: ["OOP", "DSA", "Recursion", "Sorting", "Trees", "Graphs", "Dynamic Programming"],
  },
  {
    id: "v6",
    title: "Spring Boot Tutorial for Beginners - Full Course 2024",
    channelName: "Amigoscode",
    channelId: "c6",
    thumbnail: "https://img.youtube.com/vi/9SGDpanrc8U/maxresdefault.jpg",
    duration: "3:45:20",
    durationSeconds: 13520,
    views: 1200000,
    likes: 67000,
    likeRatio: 5.58,
    sentimentScore: 88,
    syllabusMatch: 45,
    overallScore: 72,
    publishedAt: "2024-02-10",
    isPlaylist: false,
    subscriberCount: 750000,
    channelAgeYears: 6,
    description: "Learn Spring Boot from scratch. Build REST APIs and microservices.",
    topicsDetected: ["Spring Boot", "REST API", "Microservices", "JPA", "Security"],
  },
];
